language: python
python: 2.7

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34

before_install:
  - pip install codecov
install:
- pip install tox
- pip install coveralls

script: tox -e $TOX_ENV

after_success:
  - codecov
