# Config file for automatic testing at travis-ci.org

language: python

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
- pip install tox
- pip install coveralls

# command to run tests, e.g. python setup.py test
script: tox

after_success: coveralls
